# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.dispatch.v1 import dispatch_pb2 as rpc_dot_dispatch_dot_v1_dot_dispatch__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/dispatch/v1/dispatch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableWorkers = channel.unary_unary(
                '/dispatch.v1.DispatchService/ListAvailableWorkers',
                request_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersRequest.SerializeToString,
                response_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersResponse.FromString,
                _registered_method=True)
        self.ManualAssignOrder = channel.unary_unary(
                '/dispatch.v1.DispatchService/ManualAssignOrder',
                request_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderRequest.SerializeToString,
                response_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderResponse.FromString,
                _registered_method=True)
        self.ListWorkerPendingDispatches = channel.unary_unary(
                '/dispatch.v1.DispatchService/ListWorkerPendingDispatches',
                request_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesRequest.SerializeToString,
                response_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesResponse.FromString,
                _registered_method=True)
        self.ConfirmWorkerResponse = channel.unary_unary(
                '/dispatch.v1.DispatchService/ConfirmWorkerResponse',
                request_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseRequest.SerializeToString,
                response_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseResponse.FromString,
                _registered_method=True)
        self.GetOrderDispatchHistory = channel.unary_unary(
                '/dispatch.v1.DispatchService/GetOrderDispatchHistory',
                request_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryRequest.SerializeToString,
                response_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryResponse.FromString,
                _registered_method=True)


class DispatchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAvailableWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualAssignOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkerPendingDispatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmWorkerResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderDispatchHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableWorkers,
                    request_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersRequest.FromString,
                    response_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersResponse.SerializeToString,
            ),
            'ManualAssignOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualAssignOrder,
                    request_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderRequest.FromString,
                    response_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderResponse.SerializeToString,
            ),
            'ListWorkerPendingDispatches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkerPendingDispatches,
                    request_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesRequest.FromString,
                    response_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesResponse.SerializeToString,
            ),
            'ConfirmWorkerResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmWorkerResponse,
                    request_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseRequest.FromString,
                    response_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseResponse.SerializeToString,
            ),
            'GetOrderDispatchHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderDispatchHistory,
                    request_deserializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryRequest.FromString,
                    response_serializer=rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dispatch.v1.DispatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dispatch.v1.DispatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAvailableWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatch.v1.DispatchService/ListAvailableWorkers',
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersRequest.SerializeToString,
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListAvailableWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManualAssignOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatch.v1.DispatchService/ManualAssignOrder',
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderRequest.SerializeToString,
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ManualAssignOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkerPendingDispatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatch.v1.DispatchService/ListWorkerPendingDispatches',
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesRequest.SerializeToString,
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ListWorkerPendingDispatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmWorkerResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatch.v1.DispatchService/ConfirmWorkerResponse',
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseRequest.SerializeToString,
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.ConfirmWorkerResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderDispatchHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dispatch.v1.DispatchService/GetOrderDispatchHistory',
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryRequest.SerializeToString,
            rpc_dot_dispatch_dot_v1_dot_dispatch__pb2.GetOrderDispatchHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
